### ISSUE TITLE
Make it a proper Web App

### ISSUE THREAD

**Issue by CryZe** [iotku/websplit#17]
http://taylor.fausak.me/2015/01/27/ios-8-web-apps/

This makes it an actual App that has an Icon, a proper name and doesn't have the browser UI anymore, just the timer itself. (iOS only)

There's also ways to make websites fully available offline, so combining both would make it an actual offline App, which would be great. (any browser)

Android might have some similar way of creating a Web App without the browser UI.

**Comment by iotku** [comment]
Merged!

**Comment by iotku** [comment]
CryZe says it doesn't work entirely offline, so reopening. If this could be made to work that'd be pretty nice. Everything is setup to be local w/ no server dependencies or anything so it should be fairly possible.

**Comment by CryZe** [comment]
http://updates.html5rocks.com/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android
Both the Cache Manifest proposed in #25 and this would make it a full on Web App. #25 already makes it a full on Web App on iOS but Chrome / Android wants its own JSON based Manifest for it to consider it a Web App.

**Comment by iotku** [comment]
Seems to work for me (Now that I cleared of enough space on my bad phone to install chrome),

I should probably cook up an icon or something though.
