### ISSUE TITLE
Unsplitting after the timer has ended doesn't take pausing into account

### ISSUE THREAD

**Issue by iotku** [iotku/websplit#28]
Currently if you unsplit after the timer ends the time is based on the amount of time since the timer started, but doesn't take away the amount of time that the timer may have been paused, leading the timer to be set incorrectly

**Comment by CryZe** [comment]
Unsplitting in general sets the timer wrong sometimes, not quite sure how to replicate it though, but it's not just after the timer ended.

**Comment by iotku** [comment]
It seemed to work ok without pausing, but it's kinda hard to tell if it's working completely right or not which is pretty annoying. (Have to find a smart way to reliably test it, maybe websockets can help with automating that)

Unsplit while the timer is running shouldn't change the main timer's time at all, should just move the current split back one and put the old time back in its place.

Been meaning to work on it regardless, it's really messy right now.

**Comment by CryZe** [comment]
When splitting after unsplitting (a couple of times), the splitted time was
completely off the actual timer's time. That's the issue I had. No idea how
it happened though.

2015-05-25 22:18 GMT+02:00 Jonathan A. <notifications@github.com>:

**Comment by iotku** [comment]
Is this on the websockets branch or gh-pages/master (iotku.pw/iotku)?

Seems to be off for some reason on websockets, maybe something I changed did something.

Most of my final splits on websockets seem to be 0.1 different than where the timer stops

**Comment by iotku** [comment]
I'm thinking part of it is just processing delay from the time split is pressed to the time it actually pauses the timer, it doesn't explicitly stop the timer at the last split time.

Unable to reproduce anything more than a 0.1s difference or so between the final split time, but I haven't taken a screen recorder to it yet to see how different split times get.

One possibility for a more significant change could be a system time update perhaps, but the time for the splits it pulled from the same variable as the timer display so in that case it *should* still be about the same.

Anyways, I'm going to see if I can reproduce while sorting this out

**Comment by CryZe** [comment]
It was the websockets branch, but it was like more than 10 seconds off and
increased with every unsplit. It was not just delay.

2015-05-25 22:53 GMT+02:00 Jonathan A. <notifications@github.com>:

**Comment by iotku** [comment]
8bce7452b0c0e676b315c8e2de4264796c1a59b0 

Should work properly with pausing now.

Also changed from Date.now() to [performence.now()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) which might hopefully solve the issues you came across, but still haven't been able to reproduce. It's better for timing anyways as the systemclock/NTP/etc shouldn't affect it.

**Comment by iotku** [comment]
iOS Safari might not have support for performence.now(), because that would be too simple :-1:
